---
deployment:
  tasks:
    - /bin/cp -R app /home/putralim/limasputra\ -\ deploy/
    - /bin/cp -R bootstrap /home/putralim/limasputra\ -\ deploy/
    - /bin/cp -R config /home/putralim/limasputra\ -\ deploy/
    - /bin/cp -R database /home/putralim/limasputra\ -\ deploy/
    - /bin/cp -R resources /home/putralim/limasputra\ -\ deploy/
    - /bin/cp -R routes /home/putralim/limasputra\ -\ deploy/
    - /bin/cp artisan /home/putralim/limasputra\ -\ deploy/
    - /bin/cp composer.json /home/putralim/limasputra\ -\ deploy/
    - /bin/cp composer.lock /home/putralim/limasputra\ -\ deploy/